import test_RNDAGB_T65_pay_card_all_types_receipts
import test_RNDAGB_T69_receipt_outcome
import test_RNDAGB_T71_income_outcome
import test_RNDAGB_T75_open_shift
import test_RNDAGB_T78_receipt_outcome_refund
import test_RNDAGB_T82_pay_cash_all_types_receipts
import test_RNDAGB_T104_correction_receipt_outcome
import test_RNDAGB_T109_receipt_income_refund
import test_RNDAGB_T116_correction_receipt_income
import test_RNDAGB_T121_pay_combo_all_types_receipts
import test_RNDAGB_T1010_check_agents



